config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_nvim:
    dst: ~/.config/nvim
    src: config/nvim
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_profile:
    dst: ~/.profile
    src: profile
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  unified-host:
    dotfiles:
    - d_nvim
    - f_gitconfig
    - f_profile
    - f_tmux.conf
    - f_xresources
